# Generated by Django 2.0.13 on 2020-06-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='select_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fes_name', models.TextField()),
                ('fes_start_month', models.IntegerField()),
                ('fes_start_day', models.IntegerField()),
                ('fes_end_month', models.IntegerField()),
                ('fes_end_day', models.IntegerField()),
            ],
        ),
    ]
