# Generated by Django 2.0.13 on 2020-06-06 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fes_visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='select_option',
            new_name='Option',
        ),
    ]
