# Generated by Django 2.0.13 on 2020-06-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fes_visitor', '0002_auto_20200606_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result_visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitor', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='fes_end_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='fes_start_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='fes_end_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='fes_end_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='fes_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='option',
            name='fes_start_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='fes_start_month',
            field=models.IntegerField(default=0),
        ),
    ]
