# Generated by Django 2.0.13 on 2020-06-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fes_visitor', '0003_auto_20200608_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fes_name', models.TextField(default='')),
                ('fes_start_year', models.IntegerField(default=0)),
                ('fes_start_month', models.IntegerField(default=0)),
                ('fes_start_day', models.IntegerField(default=0)),
                ('fes_end_year', models.IntegerField(default=0)),
                ('fes_end_month', models.IntegerField(default=0)),
                ('fes_end_day', models.IntegerField(default=0)),
                ('total_visitor', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Result_visitor',
        ),
    ]
